export { HomePage } from './HomePage';
export { AboutPage } from './AboutPage';
export { ProductPage } from './ProductPage';
export { SolutionsPage } from './SolutionsPage';
export { PlatformPage } from './PlatformPage';
export { PartnershipsPage } from './PartnershipsPage';
export { ContactPage } from './ContactPage';
export { RegisterPage } from './RegisterPage';
export { RegisterCompletePage } from './RegisterCompletePage';
